# https://arkmowers.github.io/arknights-mower/dev/environment.html#auto-formatting

name: 代码格式检查与测试
on:
  - push
  - pull_request

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
      - uses: chartboost/ruff-action@v1
        with:
          args: "format --check"

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: creyD/prettier_action@v4.3
        with:
          dry: True
          prettier_options: "--check ui/**/*.js ui/**/*.vue"

  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: requirements.txt
      - run: |
          python3.12 -m venv venv
          ./venv/bin/pip install -r requirements.txt
      - run: |
          ./venv/bin/python3 -m unittest discover -s arknights_mower/tests -p "*_tests.py"