name: dev_shawn分支自动打包

on:
  push:
    branches:
      - dev_shawn

jobs:
  build-win-amd64:
    runs-on: windows-latest
    steps:
      - name: download frontend
        uses: actions/checkout@v3
        with:
          repository: ArkMowers/mower-ui
        working-directory: ./mower-ui
      - name: setup nodejs 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: build frontend
        working-directory: ./mower-ui
        shell: bash
        run: |
          npm install
          npm run build
          cp -r dist ..
      - uses: actions/checkout@v2
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v2
        with:
          install-only: true
      - name: Set up Python 3.8 amd64
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install dependencies
        shell: cmd
        run: |
          python -m venv venv
          venv\Scripts\python -m pip install -r requirements.txt
          venv\Scripts\python -m pip install pyinstaller
      - name: Patch Paddle
        shell: cmd
        run: |
          copy .\packaging\image.py .\venv\Lib\site-packages\paddle\dataset\image.py /y
          copy .\packaging\network.py .\venv\Lib\site-packages\paddleocr\ppocr\utils\network.py /y
          copy .\packaging\paddleocr.py .\venv\Lib\site-packages\paddleocr\paddleocr.py /y
      - name: Make package
        shell: cmd
        run: |
          venv\Scripts\pyinstaller .\webview.spec
      - uses: actions/upload-artifact@v3
        with:
          name: mower
          path: dist\mower.exe
